apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-deployment
spec:
    replicas: 4
    selector:
        matchLabels:
            app: php-server
    template:
        metadata:
            labels:
                app: php-server
        spec:
            containers:
              - name: php-apache
                image:
                ports:
                  - containerPort: 80
                resources:
                    requests:
                        cpu: 200m
                    limits:
                        cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
    name: php-apache
    labels:
        app: php-server
spec:
    selector:
        app: php-server
    ports:
      - port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-deployment
spec:
    replicas: 4
    selector:
        matchLabels:
            app: php-server
    template:
        metadata:
            labels:
                app: php-server
        spec:
            containers:
              - name: php-apache
                image:
                ports:
                  - containerPort: 80
                resources:
                    requests:
                        cpu: 200m
                    limits:
                        cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
    name: php-apache
    labels:
        app: php-server
spec:
    selector:
        app: php-server
    ports:
      - port: 80

                  